const GENDER_LIST = {
  male: 'male',
  female: 'female',
};

const COLOR_LIST = {
  black: 'black',
  red: 'red',
  yellow: 'yellow',
  orange: 'orange',
  gray: 'gray',
  pink: 'pink',
  purple: 'purple',
  brown: 'brown',
  white: 'white',
  green: 'green',
  blue: 'blue',
  other: 'other',
};

const SIZE_LIST = {
  small: 'small',
  medium: 'medium',
  large: 'large',
  extra_large: 'extra_large',
  double_extra_large: 'double_extra_large',
  triple_extra_large: 'triple_extra_large',
  quadruple_extra_large: 'quadruple_extra_large',
  quintuple_extra_large: 'quintuple_extra_large',
};

const PRODUCT_LIST = [
  {
    id: 1,
    image: '/images/products/product1.png',
    title: 'Nalya Package',
    price: 490000,
    originalPrice: 529000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.red, COLOR_LIST.gray, COLOR_LIST.white],
    size: [
      SIZE_LIST.small,
      SIZE_LIST.medium,
      SIZE_LIST.large,
      SIZE_LIST.extra_large,
      SIZE_LIST.double_extra_large,
      SIZE_LIST.triple_extra_large,
      SIZE_LIST.quadruple_extra_large,
      SIZE_LIST.quintuple_extra_large,
    ],
    slug: 'nalya-package',
    description: `
    Gói Nalya là lựa chọn hoàn hảo cho người phụ nữ tinh tế, mang lại sự kết hợp tuyệt vời giữa thiết kế hiện đại và vẻ đẹp vượt thời gian. Với dáng áo ôm nhẹ nhàng và đa dạng màu sắc như đỏ tươi, xám cổ điển, và trắng tinh khôi, sản phẩm này phù hợp với mọi phong cách. Có sẵn từ size nhỏ (S) đến siêu lớn (5XL), đảm bảo vừa vặn hoàn hảo cho mọi dáng người. Chất liệu vải cao cấp cùng sự tỉ mỉ trong từng chi tiết khiến gói sản phẩm này trở thành lựa chọn không thể bỏ qua trong bất kỳ tủ đồ nào, vừa thoải mái vừa thời trang.`,
    total_reviews: 12,
    rating: 4.5,
  },
  {
    id: 2,
    image: '/images/products/product2.png',
    title: 'Aria Dress',
    price: 550000,
    originalPrice: 600000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.pink, COLOR_LIST.white],
    size: [SIZE_LIST.small, SIZE_LIST.medium, SIZE_LIST.large, SIZE_LIST.extra_large],
    slug: 'aria-dress',
    description: `
    Chiếc váy Aria mang đến vẻ đẹp dịu dàng và nữ tính với màu hồng phấn và trắng tinh khôi. Thiết kế đơn giản nhưng tinh tế, phù hợp cho các buổi tiệc nhẹ nhàng hay dạo phố.`,
    total_reviews: 8,
    rating: 5,
  },
  {
    id: 3,
    image: '/images/products/product3.png',
    title: 'Luna Jacket',
    price: 750000,
    originalPrice: 800000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.black, COLOR_LIST.blue],
    size: [SIZE_LIST.medium, SIZE_LIST.large, SIZE_LIST.extra_large, SIZE_LIST.double_extra_large],
    slug: 'luna-jacket',
    description: `
    Áo khoác Luna mang phong cách hiện đại và mạnh mẽ, với chất liệu vải cao cấp và màu sắc đen, xanh dương. Phù hợp cho những ngày se lạnh.`,
    total_reviews: 15,
    rating: 4.5,
  },
  {
    id: 4,
    image: '/images/products/product4.png',
    title: 'Orion T-Shirt',
    price: 300000,
    originalPrice: 350000,
    gender: [GENDER_LIST.male, GENDER_LIST.female],
    color: [COLOR_LIST.green, COLOR_LIST.gray],
    size: [SIZE_LIST.small, SIZE_LIST.medium, SIZE_LIST.large],
    slug: 'orion-tshirt',
    description: `
    Áo thun Orion với thiết kế đơn giản, màu sắc tươi sáng, phù hợp cho cả nam và nữ. Chất liệu cotton thoáng mát, dễ chịu.`,
    total_reviews: 20,
    rating: 4.5,
  },
  {
    id: 5,
    image: '/images/products/product5.png',
    title: 'Stella Pants',
    price: 400000,
    originalPrice: 450000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.black, COLOR_LIST.brown],
    size: [SIZE_LIST.small, SIZE_LIST.medium, SIZE_LIST.large, SIZE_LIST.extra_large],
    slug: 'stella-pants',
    description: `
    Quần Stella với thiết kế ôm sát, chất liệu vải co giãn tốt, mang lại sự thoải mái và phong cách cho người mặc.`,
    total_reviews: 10,
    rating: 4,
  },
  {
    id: 6,
    image: '/images/products/product6.png',
    title: 'Vega Shoes',
    price: 850000,
    originalPrice: 900000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.white, COLOR_LIST.blue],
    size: [SIZE_LIST.medium, SIZE_LIST.large, SIZE_LIST.extra_large],
    slug: 'vega-shoes',
    description: `
    Giày Vega với thiết kế thể thao, màu sắc trẻ trung, phù hợp cho các hoạt động ngoài trời.`,
    total_reviews: 18,
    rating: 5,
  },
  {
    id: 7,
    image: '/images/products/product7.png',
    title: 'Nova Hat',
    price: 200000,
    originalPrice: 250000,
    gender: [GENDER_LIST.male, GENDER_LIST.female],
    color: [COLOR_LIST.red, COLOR_LIST.black],
    size: [SIZE_LIST.small, SIZE_LIST.medium, SIZE_LIST.large],
    slug: 'nova-hat',
    description: `
    Mũ Nova với thiết kế đơn giản, màu sắc nổi bật, phù hợp cho cả nam và nữ.`,
    total_reviews: 5,
    rating: 5,
  },
  // Tiếp tục tạo các sản phẩm khác từ 8 đến 30
  {
    id: 8,
    image: '/images/products/product8.png',
    title: 'Aurora Scarf',
    price: 150000,
    originalPrice: 180000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.purple, COLOR_LIST.gray],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
    slug: 'aurora-scarf',
    description: `
    Khăn quàng Aurora với chất liệu mềm mại, màu sắc tinh tế, mang lại sự ấm áp và phong cách cho người mặc.`,
    total_reviews: 7,
    rating: 5,
  },
  {
    id: 9,
    image: '/images/products/product1.png',
    title: 'Phoenix Belt',
    price: 250000,
    originalPrice: 300000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.brown, COLOR_LIST.black],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
    slug: 'phoenix-belt',
    description: `
    Thắt lưng Phoenix với thiết kế chắc chắn, chất liệu da cao cấp, phù hợp cho các dịp trang trọng.`,
    total_reviews: 12,
    rating: 4.5,
  },
  {
    id: 10,
    image: '/images/products/product2.png',
    title: 'Gemini Gloves',
    price: 180000,
    originalPrice: 220000,
    gender: [GENDER_LIST.male, GENDER_LIST.female],
    color: [COLOR_LIST.black, COLOR_LIST.gray],
    size: [SIZE_LIST.small, SIZE_LIST.medium, SIZE_LIST.large],
    slug: 'gemini-gloves',
    description: `
    Găng tay Gemini với thiết kế hiện đại, chất liệu ấm áp, phù hợp cho cả nam và nữ.`,
    total_reviews: 9,
    rating: 4.5,
  },
  // Các sản phẩm tiếp theo từ 11 đến 30
  {
    id: 11,
    image: '/images/products/product3.png',
    title: 'Leo Sunglasses',
    price: 320000,
    originalPrice: 350000,
    gender: [GENDER_LIST.male, GENDER_LIST.female],
    color: [COLOR_LIST.black, COLOR_LIST.brown],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
    slug: 'leo-sunglasses',
    description: `
    Kính mát Leo với thiết kế thời trang, bảo vệ mắt khỏi tia UV, phù hợp cho cả nam và nữ.`,
    total_reviews: 14,
    rating: 5,
  },
  {
    id: 12,
    image: '/images/products/product4.png',
    title: 'Capella Backpack',
    price: 600000,
    originalPrice: 650000,
    gender: [GENDER_LIST.male, GENDER_LIST.female],
    color: [COLOR_LIST.blue, COLOR_LIST.gray],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
    slug: 'capella-backpack',
    description: `
    Ba lô Capella với thiết kế tiện dụng, chất liệu bền bỉ, phù hợp cho các chuyến đi xa.`,
    total_reviews: 11,
    rating: 4,
  },
];

export { GENDER_LIST, COLOR_LIST, SIZE_LIST, PRODUCT_LIST };
