const GENDER_LIST = {
  male: 'male',
  female: 'female',
};

const COLOR_LIST = {
  black: 'black',
  red: 'red',
  yellow: 'yellow',
  orange: 'orange',
  gray: 'gray',
  pink: 'pink',
  purple: 'purple',
  brown: 'brown',
  white: 'white',
  green: 'green',
  blue: 'blue',
  other: 'other',
};

const SIZE_LIST = {
  small: 'small',
  medium: 'medium',
  large: 'large',
  extra_large: 'extra_large',
  double_extra_large: 'double_extra_large',
  triple_extra_large: 'triple_extra_large',
  quadruple_extra_large: 'quadruple_extra_large',
  quintuple_extra_large: 'quintuple_extra_large',
};

const PRODUCT_LIST = [
  {
    id: 1,
    image: '/images/products/product1.png',
    title: 'Nalya Package',
    price: 490000,
    originalPrice: 529000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.red, COLOR_LIST.gray, COLOR_LIST.white],
    size: [
      SIZE_LIST.small,
      SIZE_LIST.medium,
      SIZE_LIST.large,
      SIZE_LIST.extra_large,
      SIZE_LIST.double_extra_large,
      SIZE_LIST.triple_extra_large,
      SIZE_LIST.quadruple_extra_large,
      SIZE_LIST.quintuple_extra_large,
    ],
  },
  {
    id: 2,
    image: '/images/products/product2.png',
    title: 'Aria Package',
    price: 599000,
    originalPrice: 699000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.black, COLOR_LIST.white],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 3,
    image: '/images/products/product3.png',
    title: 'Lorena Package',
    price: 299000,
    originalPrice: 359000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.pink, COLOR_LIST.purple],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
  },
  {
    id: 4,
    image: '/images/products/product4.png',
    title: 'Ezra Package',
    price: 750000,
    originalPrice: 899000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.gray, COLOR_LIST.brown],
    size: [SIZE_LIST.large, SIZE_LIST.extra_large],
  },
  {
    id: 5,
    image: '/images/products/product5.png',
    title: 'Zara Package',
    price: 450000,
    originalPrice: 499000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.yellow, COLOR_LIST.pink],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
  },
  {
    id: 6,
    image: '/images/products/product6.png',
    title: 'Levi Package',
    price: 650000,
    originalPrice: 750000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.red, COLOR_LIST.white],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 7,
    image: '/images/products/product7.png',
    title: 'Ella Package',
    price: 399000,
    originalPrice: 459000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.pink, COLOR_LIST.gray],
    size: [SIZE_LIST.small, SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 8,
    image: '/images/products/product8.png',
    title: 'Odin Package',
    price: 749000,
    originalPrice: 799000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.black, COLOR_LIST.yellow],
    size: [SIZE_LIST.large, SIZE_LIST.extra_large],
  },
  {
    id: 9,
    image: '/images/products/product2.png',
    title: 'Mia Package',
    price: 520000,
    originalPrice: 589000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.red, COLOR_LIST.purple],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
  },
  {
    id: 10,
    image: '/images/products/product7.png',
    title: 'Luna Package',
    price: 320000,
    originalPrice: 399000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.white, COLOR_LIST.gray],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 11,
    image: '/images/products/product3.png',
    title: 'Max Package',
    price: 490000,
    originalPrice: 550000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.black, COLOR_LIST.brown],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 12,
    image: '/images/products/product7.png',
    title: 'Noah Package',
    price: 700000,
    originalPrice: 799000,
    gender: [GENDER_LIST.female, GENDER_LIST.male],
    color: [COLOR_LIST.orange, COLOR_LIST.gray],
    size: [SIZE_LIST.large, SIZE_LIST.extra_large],
  },
  {
    id: 13,
    image: '/images/products/product6.png',
    title: 'Sophia Package',
    price: 350000,
    originalPrice: 450000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.purple, COLOR_LIST.pink],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
  },
  {
    id: 14,
    image: '/images/products/product4.png',
    title: 'Liam Package',
    price: 499000,
    originalPrice: 599000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.white, COLOR_LIST.brown],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 15,
    image: '/images/products/product5.png',
    title: 'Ava Package',
    price: 280000,
    originalPrice: 350000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.red, COLOR_LIST.pink],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
  },
  {
    id: 16,
    image: '/images/products/product2.png',
    title: 'Olivia Package',
    price: 450000,
    originalPrice: 499000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.white, COLOR_LIST.pink],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 17,
    image: '/images/products/product1.png',
    title: 'Emma Package',
    price: 399000,
    originalPrice: 450000,
    gender: [GENDER_LIST.female, GENDER_LIST.male],
    color: [COLOR_LIST.black, COLOR_LIST.white],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 18,
    image: '/images/products/product8.png',
    title: 'James Package',
    price: 550000,
    originalPrice: 650000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.red, COLOR_LIST.gray],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 19,
    image: '/images/products/product7.png',
    title: 'Logan Package',
    price: 620000,
    originalPrice: 720000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.brown, COLOR_LIST.white],
    size: [SIZE_LIST.large, SIZE_LIST.extra_large],
  },
  {
    id: 20,
    image: '/images/products/product6.png',
    title: 'Isabella Package',
    price: 320000,
    originalPrice: 399000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.gray, COLOR_LIST.purple],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
  },
  {
    id: 21,
    image: '/images/products/product5.png',
    title: 'Lucas Package',
    price: 690000,
    originalPrice: 799000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.red, COLOR_LIST.brown],
    size: [SIZE_LIST.large, SIZE_LIST.extra_large],
  },
  {
    id: 22,
    image: '/images/products/product4.png',
    title: 'Elijah Package',
    price: 450000,
    originalPrice: 499000,
    gender: [GENDER_LIST.female, GENDER_LIST.male],
    color: [COLOR_LIST.gray, COLOR_LIST.yellow],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 23,
    image: '/images/products/product2.png',
    title: 'Amelia Package',
    price: 360000,
    originalPrice: 420000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.pink, COLOR_LIST.gray],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
  },
  {
    id: 24,
    image: '/images/products/product1.png',
    title: 'Mason Package',
    price: 720000,
    originalPrice: 820000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.red, COLOR_LIST.brown],
    size: [SIZE_LIST.large, SIZE_LIST.extra_large],
  },
  {
    id: 25,
    image: '/images/products/product3.png',
    title: 'Harper Package',
    price: 280000,
    originalPrice: 350000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.purple, COLOR_LIST.white],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
  },
  {
    id: 26,
    image: '/images/products/product7.png',
    title: 'Evelyn Package',
    price: 320000,
    originalPrice: 399000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.pink, COLOR_LIST.gray],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 27,
    image: '/images/products/product8.png',
    title: 'Benjamin Package',
    price: 500000,
    originalPrice: 599000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.black, COLOR_LIST.gray],
    size: [SIZE_LIST.large, SIZE_LIST.extra_large],
  },
  {
    id: 28,
    image: '/images/products/product1.png',
    title: 'Ella Package',
    price: 470000,
    originalPrice: 529000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.red, COLOR_LIST.pink],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
  },
  {
    id: 29,
    image: '/images/products/product2.png',
    title: 'Henry Package',
    price: 599000,
    originalPrice: 699000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.brown, COLOR_LIST.white],
    size: [SIZE_LIST.large, SIZE_LIST.extra_large],
  },
  {
    id: 30,
    image: '/images/products/product3.png',
    title: 'Avery Package',
    price: 1410000,
    originalPrice: 1459000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.purple, COLOR_LIST.gray],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
  },
  {
    id: 31,
    image: '/images/products/product1.png',
    title: 'Aurora Package',
    price: 580000,
    originalPrice: 620000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.blue, COLOR_LIST.white],
    size: [SIZE_LIST.medium, SIZE_LIST.large, SIZE_LIST.extra_large],
  },
  {
    id: 32,
    image: '/images/products/product2.png',
    title: 'Blake Package',
    price: 390000,
    originalPrice: 450000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.green, COLOR_LIST.black],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
  },
  {
    id: 33,
    image: '/images/products/product3.png',
    title: 'Chloe Package',
    price: 340000,
    originalPrice: 400000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.pink, COLOR_LIST.gray],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
  },
  {
    id: 34,
    image: '/images/products/product4.png',
    title: 'David Package',
    price: 799000,
    originalPrice: 899000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.red, COLOR_LIST.blue],
    size: [SIZE_LIST.large, SIZE_LIST.extra_large],
  },
  {
    id: 35,
    image: '/images/products/product5.png',
    title: 'Eva Package',
    price: 600000,
    originalPrice: 690000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.orange, COLOR_LIST.white],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 36,
    image: '/images/products/product6.png',
    title: 'Felix Package',
    price: 440000,
    originalPrice: 490000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.black, COLOR_LIST.white],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 37,
    image: '/images/products/product7.png',
    title: 'Grace Package',
    price: 560000,
    originalPrice: 620000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.pink, COLOR_LIST.purple],
    size: [SIZE_LIST.small, SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 38,
    image: '/images/products/product8.png',
    title: 'Harry Package',
    price: 720000,
    originalPrice: 799000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.gray, COLOR_LIST.brown],
    size: [SIZE_LIST.large, SIZE_LIST.extra_large],
  },
  {
    id: 39,
    image: '/images/products/product1.png',
    title: 'Ivy Package',
    price: 320000,
    originalPrice: 370000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.red, COLOR_LIST.purple],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
  },
  {
    id: 40,
    image: '/images/products/product2.png',
    title: 'Jack Package',
    price: 540000,
    originalPrice: 620000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.blue, COLOR_LIST.gray],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 41,
    image: '/images/products/product3.png',
    title: 'Kayla Package',
    price: 300000,
    originalPrice: 350000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.pink, COLOR_LIST.black],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
  },
  {
    id: 42,
    image: '/images/products/product4.png',
    title: 'Leo Package',
    price: 880000,
    originalPrice: 990000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.green, COLOR_LIST.yellow],
    size: [SIZE_LIST.large, SIZE_LIST.extra_large],
  },
  {
    id: 43,
    image: '/images/products/product5.png',
    title: 'Mila Package',
    price: 420000,
    originalPrice: 480000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.red, COLOR_LIST.gray],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 44,
    image: '/images/products/product6.png',
    title: 'Nora Package',
    price: 310000,
    originalPrice: 390000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.pink, COLOR_LIST.white],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
  },
  {
    id: 45,
    image: '/images/products/product7.png',
    title: 'Oscar Package',
    price: 640000,
    originalPrice: 720000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.black, COLOR_LIST.blue],
    size: [SIZE_LIST.large, SIZE_LIST.extra_large],
  },
  {
    id: 46,
    image: '/images/products/product8.png',
    title: 'Piper Package',
    price: 360000,
    originalPrice: 420000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.purple, COLOR_LIST.gray],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
  },
  {
    id: 47,
    image: '/images/products/product1.png',
    title: 'Quinn Package',
    price: 550000,
    originalPrice: 620000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.red, COLOR_LIST.yellow],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 48,
    image: '/images/products/product2.png',
    title: 'Riley Package',
    price: 440000,
    originalPrice: 510000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.green, COLOR_LIST.white],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 49,
    image: '/images/products/product3.png',
    title: 'Sofia Package',
    price: 310000,
    originalPrice: 380000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.pink, COLOR_LIST.brown],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
  },
  {
    id: 50,
    image: '/images/products/product4.png',
    title: 'Tyler Package',
    price: 750000,
    originalPrice: 820000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.blue, COLOR_LIST.gray],
    size: [SIZE_LIST.large, SIZE_LIST.extra_large],
  },
  {
    id: 51,
    image: '/images/products/product5.png',
    title: 'Uma Package',
    price: 500000,
    originalPrice: 580000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.white, COLOR_LIST.orange],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 52,
    image: '/images/products/product6.png',
    title: 'Vera Package',
    price: 480000,
    originalPrice: 550000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.red, COLOR_LIST.purple],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 53,
    image: '/images/products/product7.png',
    title: 'Will Package',
    price: 620000,
    originalPrice: 690000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.black, COLOR_LIST.blue],
    size: [SIZE_LIST.large, SIZE_LIST.extra_large],
  },
  {
    id: 54,
    image: '/images/products/product8.png',
    title: 'Xena Package',
    price: 370000,
    originalPrice: 430000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.pink, COLOR_LIST.gray],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
  },
  {
    id: 55,
    image: '/images/products/product1.png',
    title: 'Yara Package',
    price: 610000,
    originalPrice: 680000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.red, COLOR_LIST.white],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 56,
    image: '/images/products/product2.png',
    title: 'Zane Package',
    price: 420000,
    originalPrice: 480000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.gray, COLOR_LIST.brown],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 57,
    image: '/images/products/product3.png',
    title: 'Aiden Package',
    price: 680000,
    originalPrice: 760000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.green, COLOR_LIST.blue],
    size: [SIZE_LIST.large, SIZE_LIST.extra_large],
  },
  {
    id: 58,
    image: '/images/products/product4.png',
    title: 'Bella Package',
    price: 390000,
    originalPrice: 440000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.pink, COLOR_LIST.black],
    size: [SIZE_LIST.small, SIZE_LIST.medium],
  },
  {
    id: 59,
    image: '/images/products/product5.png',
    title: 'Carla Package',
    price: 470000,
    originalPrice: 520000,
    gender: [GENDER_LIST.female],
    color: [COLOR_LIST.purple, COLOR_LIST.orange],
    size: [SIZE_LIST.medium, SIZE_LIST.large],
  },
  {
    id: 60,
    image: '/images/products/product6.png',
    title: 'Dylan Package',
    price: 750000,
    originalPrice: 820000,
    gender: [GENDER_LIST.male],
    color: [COLOR_LIST.black, COLOR_LIST.yellow],
    size: [SIZE_LIST.large, SIZE_LIST.extra_large],
  },
];

export { GENDER_LIST, COLOR_LIST, SIZE_LIST, PRODUCT_LIST };
